%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-robot-localization
Version:        3.9.2
Release:        3%{?dist}%{?release_suffix}
Summary:        ROS robot_localization package

License:        Apache License 2.0
URL:            http://ros.org/wiki/robot_localization
Source0:        %{name}-%{version}.tar.gz

Requires:       GeographicLib-devel
Requires:       boost-devel
Requires:       eigen3-devel
Requires:       ros-kilted-angles
Requires:       ros-kilted-builtin-interfaces
Requires:       ros-kilted-diagnostic-msgs
Requires:       ros-kilted-diagnostic-updater
Requires:       ros-kilted-geographic-msgs
Requires:       ros-kilted-geometry-msgs
Requires:       ros-kilted-message-filters
Requires:       ros-kilted-nav-msgs
Requires:       ros-kilted-rclcpp
Requires:       ros-kilted-rosidl-default-runtime
Requires:       ros-kilted-sensor-msgs
Requires:       ros-kilted-std-msgs
Requires:       ros-kilted-std-srvs
Requires:       ros-kilted-tf2
Requires:       ros-kilted-tf2-eigen
Requires:       ros-kilted-tf2-geometry-msgs
Requires:       ros-kilted-tf2-ros
Requires:       ros-kilted-yaml-cpp-vendor
Requires:       ros-kilted-ros-workspace
BuildRequires:  GeographicLib-devel
BuildRequires:  boost-devel
BuildRequires:  eigen3-devel
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-angles
BuildRequires:  ros-kilted-builtin-interfaces
BuildRequires:  ros-kilted-diagnostic-msgs
BuildRequires:  ros-kilted-diagnostic-updater
BuildRequires:  ros-kilted-geographic-msgs
BuildRequires:  ros-kilted-geometry-msgs
BuildRequires:  ros-kilted-message-filters
BuildRequires:  ros-kilted-nav-msgs
BuildRequires:  ros-kilted-rclcpp
BuildRequires:  ros-kilted-rosidl-default-generators
BuildRequires:  ros-kilted-sensor-msgs
BuildRequires:  ros-kilted-std-msgs
BuildRequires:  ros-kilted-std-srvs
BuildRequires:  ros-kilted-tf2
BuildRequires:  ros-kilted-tf2-eigen
BuildRequires:  ros-kilted-tf2-geometry-msgs
BuildRequires:  ros-kilted-tf2-ros
BuildRequires:  ros-kilted-yaml-cpp-vendor
BuildRequires:  ros-kilted-ros-workspace
BuildRequires:  ros-kilted-rosidl-typesupport-fastrtps-c
BuildRequires:  ros-kilted-rosidl-typesupport-fastrtps-cpp
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}
Provides:       ros-kilted-rosidl-interface-packages(member)

%if 0%{?with_tests}
BuildRequires:  ros-kilted-ament-cmake-gtest
BuildRequires:  ros-kilted-ament-lint-auto
BuildRequires:  ros-kilted-ament-lint-common
BuildRequires:  ros-kilted-launch-ros
BuildRequires:  ros-kilted-launch-testing-ament-cmake
%endif

%if 0%{?with_weak_deps}
Supplements:    ros-kilted-rosidl-interface-packages(all)
%endif

%description
Provides nonlinear state estimation through sensor fusion of an abritrary number
of sensors.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue Apr 22 2025 Tom Moore <ayrton04@gmail.com> - 3.9.2-3
- Autogenerated by Bloom

* Fri Mar 21 2025 Tom Moore <ayrton04@gmail.com> - 3.9.2-2
- Autogenerated by Bloom

* Fri Mar 21 2025 Tom Moore <ayrton04@gmail.com> - 3.9.2-1
- Autogenerated by Bloom

* Thu Aug 29 2024 Tom Moore <ayrton04@gmail.com> - 3.9.1-1
- Autogenerated by Bloom

* Wed Apr 24 2024 Tom Moore <ayrton04@gmail.com> - 3.9.0-1
- Autogenerated by Bloom

* Sun Apr 21 2024 Tom Moore <ayrton04@gmail.com> - 3.8.0-1
- Autogenerated by Bloom

* Tue Apr 16 2024 Tom Moore <ayrton04@gmail.com> - 3.6.1-1
- Autogenerated by Bloom

* Tue Mar 19 2024 Tom Moore <ayrton04@gmail.com> - 3.6.0-3
- Autogenerated by Bloom

* Wed Mar 06 2024 Tom Moore <ayrton04@gmail.com> - 3.6.0-2
- Autogenerated by Bloom

